#!/usr/bin/env bash
# Configures Nginx and redirection

# starting install nginx
sudo apt-get update -y -qq && \
	         sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Creating new index
sudo echo -e "Hello World!" | dd status=none of=/var/www/html/index.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
echo "Reloading Nginx..."
sudo systemctl reload nginx

echo "Redirection setup completed successfully."
