#!/usr/bin/env bash
# Configures Nginx and redirection 301

# Update package lists and install nginx
sudo apt-get update -y -qq && sudo apt-get install nginx -y

# Start the Nginx service
sudo systemctl start nginx

# Allow Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Create a new index file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Setting up /redirect_me to redirect to a YouTube video
sudo sed -i '/^server {/a \\tlocation = /redirect_me {\n\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
echo "Reloading Nginx..."
sudo systemctl restart nginx

echo "Redirection setup completed successfully."

