#!/usr/bin/env bash
# Installs, configures, and starts the server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"
sudo bash -c "echo 'Ceci n/'est pas une page' > /var/www/html/404.html"
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me) {
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4; permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"
sudo bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-avai/default"
if [ "$(pgrep -c nginx)" -le 0 ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
