#!/usr/bin/env bash
# Installs and setup HAProxy

# Install necessary packages
sudo apt-get update
sudo apt-get install -y software-properties-common

# Add HAProxy repository and install HAProxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9
sudo apt-get update
sudo apt-get install -y haproxy=2.9.*

# Enable HAProxy
sudo echo "ENABLED=1" > /etc/default/haproxy

sudo sed -i "$a\/frontend webF\n\tbind *:80\n\tmode http\n\tdefault_backend webB\nbackend webB\n\tmode http\n\tbalance roundrobin\n\tserver 389182-web-01 54.173.204.114:80 check\n\tserver 389182-web-02 18.214.88.79:80 check" /etc/haproxy/haproxy.cfg

# Start HAProxy service
sudo service haproxy start
