#!/usr/bin/env bash
# script that fix Nginx port 80 issue
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"
